#!/bin/sh

### BEGIN INIT INFO
# Provides:			 ProxyAnalysis
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ProxyAnalysis init script
# Description:       This script used to start/stop ProxyAnalysis
### END INIT INFO

NAME=ProxyAnalysis
DESC="${NAME} server"
PIDFILE="/var/tmp/${NAME}.pid"
EXEC=/opt/ProxyAnalysis/RecordServer.py

start() {
	echo "Starting ${DESC} ..."
    start-stop-daemon --background \
                      --make-pidfile \
                      --pidfile ${PIDFILE} \
                      --chuid nobody:nogroup \
                      --startas ${EXEC} \
                      --start
}

stop() {
	echo "Stopping ${DESC} ..."
    start-stop-daemon --pidfile ${PIDFILE} \
                      --user nobody \
                      --stop
    [ -f ${PIDFILE} ] && rm ${PIDFILE}
}

case "$1" in
  start)
	start
	;;

  stop)
	stop
	;;

  restart|force-reload)
	stop
	start
	;;

  *)
	N=/etc/init.d/${NAME}
	echo "Usage: service ${NAME} {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
